# Generated by Django 3.2.15 on 2022-11-29 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0048_auto_20221129_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 17, 33, 42, 743712, tzinfo=utc)),
        ),
    ]
